
default: &default
  adapter: mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("THE_MAP_SHOP_DB_USER") { 'root' } %>
  password: <%= ENV.fetch("THE_MAP_SHOP_DB_PASS") { 'password' } %>
  host:     <%= ENV.fetch("THE_MAP_SHOP_DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: the_map_shop_development

test:
  <<: *default
  database: the_map_shop_test

production:
  <<: *default
  database: the_map_shop_production
